{% set version = "1.2-15" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mgm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mgm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mgm/mgm_{{ version }}.tar.gz
  sha256: 40746dc3fa1c3723607e9ed04f1a95d71a0acec80817b4a5efd94b0912900a04

build:
  number: 0
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-hmisc
    - r-glmnet
    - r-gtools
    - r-qgraph
    - r-stringr

  run:
    - r-base
    - r-hmisc
    - r-glmnet
    - r-gtools
    - r-qgraph
    - r-stringr

test:
  commands:
    - $R -e "library('mgm')"           # [not win]
    - "\"%R%\" -e \"library('mgm')\""  # [win]

about:
  home: https://arxiv.org/abs/1510.06871

  license: GPL-2.0-or-later
  summary: Estimation of k-Order time-varying Mixed Graphical Models and mixed VAR(p) models via elastic-net regularized neighborhood regression. For details see Haslbeck & Waldorp (2020) <doi:10.18637/jss.v093.i08>.

  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
